version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gocritic
    - misspell
  settings:
    gocritic:
      enabled-checks:
        - appendAssign
        - argOrder
        - badCall
        - badCond
        - dupArg
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - elseif
        - exitAfterDefer
        - flagDeref
        - nilValReturn
        - sloppyLen
        - switchTrue
        - typeSwitchVar
        - underef
        - unlambda
    misspell:
      locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
